/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardRouteImport } from './routes/$board'
import { Route as ApiProxyRouteImport } from './routes/api/proxy'
import { Route as BoardThreadIdRouteImport } from './routes/$board_.thread.$id'
import { Route as ApiIpxSplatRouteImport } from './routes/api/ipx/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/$board',
  path: '/$board',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: '/api/proxy',
  path: '/api/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardThreadIdRoute = BoardThreadIdRouteImport.update({
  id: '/$board_/thread/$id',
  path: '/$board/thread/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpxSplatRoute = ApiIpxSplatRouteImport.update({
  id: '/api/ipx/$',
  path: '/api/ipx/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$board': typeof BoardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/$board/thread/$id': typeof BoardThreadIdRoute
  '/api/ipx/$': typeof ApiIpxSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$board': typeof BoardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/$board/thread/$id': typeof BoardThreadIdRoute
  '/api/ipx/$': typeof ApiIpxSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$board': typeof BoardRoute
  '/api/proxy': typeof ApiProxyRoute
  '/$board_/thread/$id': typeof BoardThreadIdRoute
  '/api/ipx/$': typeof ApiIpxSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/$board' | '/api/proxy' | '/$board/thread/$id' | '/api/ipx/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$board' | '/api/proxy' | '/$board/thread/$id' | '/api/ipx/$'
  id:
    | '__root__'
    | '/'
    | '/$board'
    | '/api/proxy'
    | '/$board_/thread/$id'
    | '/api/ipx/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  ApiProxyRoute: typeof ApiProxyRoute
  BoardThreadIdRoute: typeof BoardThreadIdRoute
  ApiIpxSplatRoute: typeof ApiIpxSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$board': {
      id: '/$board'
      path: '/$board'
      fullPath: '/$board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy': {
      id: '/api/proxy'
      path: '/api/proxy'
      fullPath: '/api/proxy'
      preLoaderRoute: typeof ApiProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$board_/thread/$id': {
      id: '/$board_/thread/$id'
      path: '/$board/thread/$id'
      fullPath: '/$board/thread/$id'
      preLoaderRoute: typeof BoardThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ipx/$': {
      id: '/api/ipx/$'
      path: '/api/ipx/$'
      fullPath: '/api/ipx/$'
      preLoaderRoute: typeof ApiIpxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  ApiProxyRoute: ApiProxyRoute,
  BoardThreadIdRoute: BoardThreadIdRoute,
  ApiIpxSplatRoute: ApiIpxSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
